[package]
name = "mqtt_data_generator"
version = "0.1.0"
authors = ["Sam Dillard <sam@influxdata.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
paho-mqtt = "0.9"
rand = "0.8.4"

